### ISSUE TITLE
New Audio Helper crash

### ISSUE THREAD

**Issue by buyddy** [zhen-zen/YogaSMC#102]
Application Specific Information:
Fatal error: 'try!' expression unexpectedly raised an error: YogaSMCNC.AudioPropertyError.emptyResult: file YogaSMCNC/AudioHelper.swift, line 112
 

I think the most recent change in audio helper fails to initiate on these 

let inputDevice = try! AudioProperty<AudioDeviceID>(device: nil, emptyValue: nil, prop: defaultInputDeviceProp).get().get()
let outputDevice = try! AudioProperty<AudioDeviceID>(device: nil, emptyValue: nil, prop: defaultOutputDeviceProp).get().get()

**Comment by zhen-zen** [comment]
Actually that's why I put them in a separate class before. This part should be model independent but I'm not sure what's going wrong.

**Comment by zhen-zen** [comment]
Will the product from last commit in #88 work?

**Comment by buyddy** [comment]
Looks like the most recent one fix this issue!
