### ISSUE TITLE
CapsLock assigned to switch keyboard layout issue

### ISSUE THREAD

**Issue by vnln** [zhen-zen/YogaSMC#104]
Is there an option to hide capslock state when clicking capslock to switch layout, but show it when you actually activating CapsLock mode by long press or shift+capslock, cmd+capslock, etc.

https://user-images.githubusercontent.com/71157087/103155187-2f7a8a00-47d8-11eb-951f-4155235af7a0.mov

**Comment by zhen-zen** [comment]
Have you tried the build from linked PR?

**Comment by vnln** [comment]
Yep, testing at the moment. Working great so far, thanks.
