### ISSUE TITLE
Lenovo Legion Y540

### ISSUE THREAD

**Issue by encoreisone** [zhen-zen/YogaSMC#11]
Hi

Is it possible to make it work on the lenovo legion y540-15irh?

Best regards 
encore

**Comment by zhen-zen** [comment]
Typically the driver should just work with common features enabled for Ideapad (all product lines besides Thinkpad) and Thinkpad family. Is there something wrong on yours? Can you provide a DSDT/SSDT dump if the driver is not loading or matching?

**Comment by encoreisone** [comment]
I have enable battery conservation mode on but its doesn't work as on my windows with Lenovo Vantage its working fine, its stay 60%.

Here is my DSDT.

![batterymode](https://user-images.githubusercontent.com/71823355/94209969-d3008980-fecd-11ea-822f-4fb5ceffd066.jpg)

[DSDT.txt](https://github.com/zhen-zen/YogaSMC/files/5279737/DSDT.txt)

**Comment by zhen-zen** [comment]
Related method calling is the same with Linux driver,

**Comment by zhen-zen** [comment]
There's a verification for `SBMC` in your DSDT. If the prerequisite is not met, the method won't proceed.

```
                    Method (SBMC, 1, NotSerialized)
                    {
                        If (ECAV)
                        {
                            If ((Acquire (LFCM, 0xA000) == Zero))
                            {
                                If ((Arg0 == Zero))
                                {
                                    CDMB = Zero
                                    EDCC = One
                                    Release (LFCM)
                                    Return (Zero)
                                }

                                If ((Arg0 == One))
                                {
                                    CDMB = One
                                    Release (LFCM)
                                    Return (Zero)
                                }

                                If ((Arg0 == 0x03))
                                {
                                    BTSM = One
                                    Release (LFCM)
                                    Return (Zero)
                                }

                                If ((Arg0 == 0x05))
                                {
                                    BTSM = Zero
                                    Release (LFCM)
                                    Return (Zero)
                                }

                                If ((Arg0 == 0x07))
                                {
                                    QCHO = One
                                    BTSM = Zero
                                    Release (LFCM)
                                    Return (Zero)
                                }

                                If ((Arg0 == 0x08))
                                {
                                    QCHO = Zero
                                    Release (LFCM)
                                    Return (Zero)
                                }

                                If ((Arg0 == 0x09))
                                {
                                    ESMC = One
                                    Release (LFCM)
                                    Return (Zero)
                                }

                                If ((Arg0 == 0x10))
                                {
                                    ESMC = Zero
                                    Release (LFCM)
                                    Return (Zero)
                                }

                                Release (LFCM)
                            }
                        }

                        Return (Zero)
                    }
```

Can you try `ioio -s IdeaVPC ReadECName ECAV` and check its value in log?

**Comment by zhen-zen** [comment]
Sorry, my bad. I added a lock for conservation mode when testing SMC key interaction. Can you try the latest build in Github Action?

**Comment by encoreisone** [comment]
Just tried the latest build, still not working for me. 

_Here are my log_:

![log1](https://user-images.githubusercontent.com/71823355/94336918-ea7f6580-ffe6-11ea-86fa-1bd5b7ff5992.png)

also how do you install pref pane correctly way? I ran the it and it said "Coud not load..."

![log2](https://user-images.githubusercontent.com/71823355/94337101-3088f900-ffe8-11ea-8fde-1433c1808685.png)

**Comment by encoreisone** [comment]
Just tried the latest build, its working now. Thanks for helping me :)

_Here are my log_:

![log3](https://user-images.githubusercontent.com/71823355/94338277-44852880-fff1-11ea-948b-695c576083b0.png)


How do you install pref pane correctly way? I ran it and it said "Coud not load..."

![log2](https://user-images.githubusercontent.com/71823355/94337101-3088f900-ffe8-11ea-8fde-1433c1808685.png)

**Comment by zhen-zen** [comment]
Yes, since it is not signed. You can use `xattr -c YogaSMCPane.prefPane` to clear the quarantine attribute before open it.

**Comment by encoreisone** [comment]
i've tried above command and also tried "sudo xattr -r -d com.apple.quarantine YogaSMCPane.prefPane"

It still said "Could not load.."  ¯\_(ツ)_/¯

**Comment by encoreisone** [comment]
i've tried above command and also tried `sudo xattr -r -d com.apple.quarantine YogaSMCPane.prefPane`

It still said "Could not load.."     `¯\_(ツ)_/¯`

**Comment by zhen-zen** [comment]
Can you try the latest build in #12 and filter the system log with keyword `YogaSMCPane`?

**Comment by zhen-zen** [comment]
Not sure what's going wring with CLI build. 
[YogaSMCPane.prefPane.zip](https://github.com/zhen-zen/YogaSMC/files/5287557/YogaSMCPane.prefPane.zip)

**Comment by encoreisone** [comment]
My gatekeeper is disabled. I still got the same message :/

![Screenshot 2020-09-27 at 12 06 35](https://user-images.githubusercontent.com/71823355/94362313-bf664600-00ba-11eb-92ad-d98a9df88364.png)

**Comment by encoreisone** [comment]
My gatekeeper is disabled. I still got the same message :/

![screen1](https://user-images.githubusercontent.com/71823355/94362397-474c5000-00bb-11eb-8056-4b4f90364c79.jpg)

**Comment by zhen-zen** [comment]
I suppose the kext should match all information that the prefpane requested. And it should still load if any property is missing. Could you take a screenshot of IdeaVPC entries in ioreg? Maybe a binary search is necessary to locate the culprit.

**Comment by encoreisone** [comment]
Here are my ioreg log

[ioreg.txt](https://github.com/zhen-zen/YogaSMC/files/5291265/ioreg.txt)

**Comment by encoreisone** [comment]
Here are my ioreg log

[ioreg.txt](https://github.com/zhen-zen/YogaSMC/files/5291323/ioreg.txt)

![log1](https://user-images.githubusercontent.com/71823355/94416925-c1dea380-017f-11eb-891e-dba4c397013f.png)
![log2](https://user-images.githubusercontent.com/71823355/94416954-c86d1b00-017f-11eb-81ec-bf9ca99413e7.png)
![log3](https://user-images.githubusercontent.com/71823355/94416987-cefb9280-017f-11eb-86f1-d04e570b6219.png)
![log4](https://user-images.githubusercontent.com/71823355/94416999-d327b000-017f-11eb-99ea-8dc90c3c6b57.png)
![log4b](https://user-images.githubusercontent.com/71823355/94417017-d7ec6400-017f-11eb-999f-f02a863cf863.png)
![log5](https://user-images.githubusercontent.com/71823355/94417028-da4ebe00-017f-11eb-989e-fedf2eae3d93.png)

**Comment by zhen-zen** [comment]
Actually the screenshot of `IdeaVPC` properties is skipped exactly. Can you send a screenshot only for that and expand the `Capability` dictionary?  The latest commit on `master` should have allowed missing value for that. But I still wonder why they are missing.

**Comment by encoreisone** [comment]
Is this correct? Am I missing something?

![ideavpc](https://user-images.githubusercontent.com/71823355/94656930-0a719a80-0301-11eb-80c7-bd2f320c7d0a.png)

**Comment by zhen-zen** [comment]
Yes... I'm not sure why Capability is not recognized, and there are some invalid values, maybe related method's not patched? Do you have working battery status?

**Comment by encoreisone** [comment]
Battery status looks normal to me 

![batstaus](https://user-images.githubusercontent.com/71823355/94746966-2ebf8c80-037e-11eb-85e9-38732efd8b5f.png)

**Comment by zhen-zen** [comment]
It seems that related methods vary from different series? Can you try the latest debug version kext and prefpane?

**Comment by encoreisone** [comment]
It seems it is working now =)

 Thank you for your help.  I truly appreciate your hard work.

![works1](https://user-images.githubusercontent.com/71823355/94793916-7aecea00-03db-11eb-8a5d-6cfff0cff180.jpg)

**Comment by zhen-zen** [comment]
Release version should work now. It seems that the kext is loaded too early that some properties are not available at that time. Maybe reset or equivalent method will be performed in pref pane.

**Comment by encoreisone** [comment]
Works as expected, thanks.
