### ISSUE TITLE
Lenovo L340 Gaming not full support ?

### ISSUE THREAD

**Issue by HandaTakuya** [zhen-zen/YogaSMC#119]
![Screen Shot 2564-02-14 at 22 33 38](https://user-images.githubusercontent.com/47761725/107881084-3048b600-6f15-11eb-9b44-2a246aa2ca36.png)
![Screen Shot 2564-02-14 at 22 37 33](https://user-images.githubusercontent.com/47761725/107881091-3c347800-6f15-11eb-997e-c5b6d8502626.png)

I use only YogaSMC 
I can unlock option of keyboard Backlight, DYTC, Function Key and Fan control ?

**Comment by zhen-zen** [comment]
Available functions depends on specific models. Please attach ACPI and ioreg dump.

**Comment by HandaTakuya** [comment]
[Jakkapan’s MacBook Pro.zip](https://github.com/zhen-zen/YogaSMC/files/5978450/Jakkapan.s.MacBook.Pro.zip)

[ACPI.zip](https://github.com/zhen-zen/YogaSMC/files/5978454/ACPI.zip)

I'm not sure to export ACPI.

**Comment by zhen-zen** [comment]
According to your DSDT, always on USB and conventional keyboard backlight control are not supported.
```
Method (HALS, 0, NotSerialized)
{
    Local0 = Zero
    If (ECAV)
    {
        If ((Acquire (LFCM, 0xA000) == Zero))
        {
            Local0 |= 0x08
            Local0 |= 0x0200
            If (HKDB)
            {
                Local0 |= 0x0400
            }

            Local0 |= 0x0800
            If (((SPMO == One) && (SPMT == Zero)))
            {
                Local0 |= 0x2000
            }

            Release (LFCM)
        }
    }

    Return (Local0)
}
```
https://github.com/zhen-zen/YogaSMC/blob/master/YogaSMC/YogaVPC/IdeaVPC.hpp#L47-L53

And DYTC method is not available on your laptop.

For function key support, you will need the NC app in the dmg in user-space as well.

Fan control on idea variant is not implemented due to lack of document.

**Comment by HandaTakuya** [comment]
> According to your DSDT, always on USB and conventional keyboard backlight control are not supported.
> 
> ```
> Method (HALS, 0, NotSerialized)
> {
>     Local0 = Zero
>     If (ECAV)
>     {
>         If ((Acquire (LFCM, 0xA000) == Zero))
>         {
>             Local0 |= 0x08
>             Local0 |= 0x0200
>             If (HKDB)
>             {
>                 Local0 |= 0x0400
>             }
> 
>             Local0 |= 0x0800
>             If (((SPMO == One) && (SPMT == Zero)))
>             {
>                 Local0 |= 0x2000
>             }
> 
>             Release (LFCM)
>         }
>     }
> 
>     Return (Local0)
> }
> ```
> 
> https://github.com/zhen-zen/YogaSMC/blob/master/YogaSMC/YogaVPC/IdeaVPC.hpp#L47-L53
> 
> And DYTC method is not available on your laptop.
> 
> For function key support, you will need the NC app in the dmg in user-space as well.
> 
> Fan control on idea variant is not implemented due to lack of document.
> 
> To read battery information, you will need to apply the same battery patch to `GBID` method.

Ohh! thank you, and my hackintosh can enable EC Access basic to RW ?

**Comment by zhen-zen** [comment]
Just check SSDTSample/SSDT-ECRW.dsl in the release.
