### ISSUE TITLE
Fan control using ThinkVPC properties

### ISSUE THREAD

**Issue by wrobeljakub** [zhen-zen/YogaSMC#126]
Is it possible to set a fan speed by setting a ThinkVPC property with `ioio`? I managed to read the speed from EC using `ioio -s YogaVPC ReadECOffset 0x84`. However I have no idea how to write a new value.

**Comment by zhen-zen** [comment]
Generic EC field write through `ioio` is not developed and also dangerous. However, that could be achieved by following the implementation in ThinkFanHelper.swift .

Specific to Fan speed control, I can add a property to trigger by `ioio`.

**Comment by zhen-zen** [comment]
Please check whether it works as intended.

**Comment by wrobeljakub** [comment]
> Please check whether it works as intended.

Yes, it suits my needs. Thank you!
