### ISSUE TITLE
EC Access Unavailable

### ISSUE THREAD

**Issue by StrikeSNC** [zhen-zen/YogaSMC#127]
When I start the app, it shows a message very quickly around "EC access Unavailable, see SSDT_ECRW.dsl".
Preferences pane has ECAccess as "Basic".
Is there any SSDTs/Kexts I will have to get? 
I am currently using Lenovo Yoga 260.

**Comment by zhen-zen** [comment]
Please check SSDT-ECRW.dsl in SSDTSample.
Currently the random EC read / write support is only used by Thinkpad models for fan speed control. However, it's also possible to dump EC map with it.
