### ISSUE TITLE
Flex 15IML won't boot after 1.5.0

### ISSUE THREAD

**Issue by Chris2fourlaw** [zhen-zen/YogaSMC#136]
After updating to 1.5.0, I'm unable to boot without disabling the kext in the config.plist

Looks ACPI related

![IMG_6936](https://user-images.githubusercontent.com/7269141/118859076-acdd8e80-b88e-11eb-8611-a0f6e8b48db7.jpeg)

[EFI.zip](https://github.com/zhen-zen/YogaSMC/files/6510707/EFI.zip)

**Comment by zhen-zen** [comment]
Hello, EFI file is not helpful since it's only a set of configuration and contains few model-specific information. Can you attach ACPI dump and a copy of ioreg with previous version?

**Comment by Chris2fourlaw** [comment]
Attached
[IoregACPI.zip](https://github.com/zhen-zen/YogaSMC/files/6512470/IoregACPI.zip)

**Comment by zhen-zen** [comment]
I guess something went wrong when populating WMI devices. Can you try the debug build here: https://github.com/zhen-zen/YogaSMC/actions/runs/844295415 ?

**Comment by Ab2774** [comment]
Hi @zhen-zen, I did test the debug build and it works perfectly.
Thanks

**Comment by Chris2fourlaw** [comment]
With the debug version 

![image](https://user-images.githubusercontent.com/7269141/119004630-95aca880-b943-11eb-9b57-9f9640bbb3ab.jpeg)

**Comment by zhen-zen** [comment]
> Hi @zhen-zen, I did test the debug build and it works perfectly.
> Thanks

Did you also get issues with latest release?

> With the debug version
> 
> ![image](https://user-images.githubusercontent.com/7269141/119004630-95aca880-b943-11eb-9b57-9f9640bbb3ab.jpeg)

This seem to be an issue related to WMI handling but I thought I have fixed that one. Can you try the latest debug version? I should have asked you to try that first.

**Comment by Chris2fourlaw** [comment]
Testing more, it's pretty intermittent when it happens. Around half the time it boots normally with the debug version, but even on those I see some info errors for "Failed to evaluate BMF data". 

Here is a screenshot of when I can't get it to boot:
![image](https://user-images.githubusercontent.com/7269141/119080363-cb3aab80-b9ae-11eb-81f1-646a49fa28e3.jpeg)

**Comment by Chris2fourlaw** [comment]
The above is on the latest debug

**Comment by zhen-zen** [comment]
I'm sorry for the inconvenience. It's a bit hard to find out where's going wrong.

So what I get is:

1. Boot without issue with 1.4.3
2. Since the CI build above, including the release one, there's possibility that kext will hang.

Please correct me if something's wrong.

Also, could you add https://github.com/acidanthera/DebugEnhancer and dump the log with `sudo dmesg | grep YSMC` after a successful boot with latest debug kext?

**Comment by Chris2fourlaw** [comment]
Correct. dmesg output here: https://pastebin.com/imwWY2VU

Time for me to sleep, got a calculus midterm in the morning. I will try your next steps after that

**Comment by Chris2fourlaw** [comment]
My thoughts:

Matching the following with my provided screenshots
```
[    2.724995]: YSMC - Debug: WMI2::YogaWMI Starting
[    2.724997]: YSMC - Info: WMI2::WMI2 Failed to evaluate BMF data
[    2.725279]: YSMC - Debug: EC0::IdeaSMC Starting
```

The last line seems to fail to print midline. My laptop is an IdeaPad Flex 15IML. Maybe the issue is with IdeaSMC?

**Comment by zhen-zen** [comment]
If there's something wrong with YogaSMC, you can try YogaSMCAlter.kext . This version doesn't have SMC functionality. Not sure why it will cause intermittent kp.

**Comment by zhen-zen** [comment]
Trying to refactor some SMC related code in #138 . I thought I already made that change but unable to find them.

**Comment by Chris2fourlaw** [comment]
I'll test the latest built a bit and see if it fixes it

**Comment by zhen-zen** [comment]
Can you try the latest release build in master branch? It should be available in https://github.com/zhen-zen/YogaSMC/actions/runs/867253917

**Comment by Chris2fourlaw** [comment]
Looks like it's booting, I've attached the debug output again. The preference pane seems to think it's a ThinkPad maybe...
https://pastebin.com/FpRMQmjz

![image](https://user-images.githubusercontent.com/7269141/119240863-7d858680-bb07-11eb-9273-dd9921c39fe5.png)

**Comment by Chris2fourlaw** [comment]
Just rebooted and it failed again
![image](https://user-images.githubusercontent.com/7269141/119240908-eec53980-bb07-11eb-8b07-abeb3fa47c42.jpeg)

**Comment by zhen-zen** [comment]
> Looks like it's booting, I've attached the debug output again. The preference pane seems to think it's a ThinkPad maybe...

You need to switch to General or Idea tab. The debug prefpane has sub-panel for all variants enabled.



> Just rebooted and it failed again
> ![image](https://user-images.githubusercontent.com/7269141/119240908-eec53980-bb07-11eb-8b07-abeb3fa47c42.jpeg)

Will continue looking into this.

**Comment by Chris2fourlaw** [comment]
> You need to switch to General or Idea tab. The debug prefpane has sub-panel for all variants enabled.

Ah makes sense. Let me know if you need anything else from my computer

**Comment by zhen-zen** [comment]
> > You need to switch to General or Idea tab. The debug prefpane has sub-panel for all variants enabled.
> 
> Ah makes sense. Let me know if you need anything else from my computer

Sorry, issues mixed up and I forgot to mention the Alter version. Can you try `YogaSMCAlter` instead to help isolate the issue? Thanks!

**Comment by Chris2fourlaw** [comment]
Alter seems to work fine
https://pastebin.com/chxcvbbP

**Comment by zhen-zen** [comment]
It's weird. So IdeaSMC is about to start at that point, the init is also good.... Can you try this one?

[YogaSMC_log.kext.zip](https://github.com/zhen-zen/YogaSMC/files/6527324/YogaSMC_log.kext.zip)

**Comment by Chris2fourlaw** [comment]
https://pastebin.com/sNPpLZB5
Here is a successful boot

**Comment by Chris2fourlaw** [comment]
Unsuccessful:
![image](https://user-images.githubusercontent.com/7269141/119251591-252ca400-bb5c-11eb-8c3d-e2dfe45d46c8.jpeg)

Also there's this EC timeout thing that might be relevant
![image](https://user-images.githubusercontent.com/7269141/119251602-34135680-bb5c-11eb-96b3-afcc8f5e142f.jpeg)

**Comment by zhen-zen** [comment]
Thanks! I guess we are close to the point. Tried to make some changes, not sure if it could help that.
[YogaSMC_poller.kext.zip](https://github.com/zhen-zen/YogaSMC/files/6527855/YogaSMC_poller.kext.zip)

**Comment by Chris2fourlaw** [comment]
Failed:
![image](https://user-images.githubusercontent.com/7269141/119255657-d7229b00-bb71-11eb-985c-d282138c82a9.jpeg)

Successful:
https://pastebin.com/wu2qFLBX

**Comment by zhen-zen** [comment]
Found a possible culprit that setPowerState could be executed before the poller is initialized. Can you try this one?

[YogaSMC_ready.kext.zip](https://github.com/zhen-zen/YogaSMC/files/6528671/YogaSMC_ready.kext.zip)

**Comment by Chris2fourlaw** [comment]
Successful:
https://pastebin.com/kYnjts5C

I restarted like 6 times and can't get it to crash. I'll let you know if it starts doing it again

**Comment by zhen-zen** [comment]
Cool, we got it! Thank you for being so patient!

**Comment by Chris2fourlaw** [comment]
No problem :)

**Comment by zhen-zen** [comment]
By the way, is the battery cycle and ID recognized correctly for your model? Do you mind upload a copy of current ioreg? Also it seems that the battery patch is not required?

**Comment by Chris2fourlaw** [comment]
Yeah, my battery was recognized by VirtualSMC's SMCBatteryManager.kext automatically

![image](https://user-images.githubusercontent.com/7269141/119273447-d7e21e00-bbbf-11eb-8ea2-7fffb8255623.png)

IOReg:
[Chris’s MacBook Pro.zip](https://github.com/zhen-zen/YogaSMC/files/6528762/Chris.s.MacBook.Pro.zip)

**Comment by zhen-zen** [comment]
[YogaSMC_info.kext.zip](https://github.com/zhen-zen/YogaSMC/files/6528845/YogaSMC_info.kext.zip)

Can you try if this fixed the two unknown field?

**Comment by Chris2fourlaw** [comment]
![image](https://user-images.githubusercontent.com/7269141/119275363-6c9d4980-bbc9-11eb-89a7-5ae15a79eb5e.png)

Works!

**Comment by zhen-zen** [comment]
Thanks! Could you attach another ioreg for this working one? I guess this issue is done then and feel free to join the gutter chat.

I'm planning to release 1.5.1 today at https://github.com/zhen-zen/YogaSMC/commit/be713b7aed14dcaf9cf171c135c88ccd42f3e94c. The release version there should be the same as local build I tested.

I was a bit rushed to test the release kext for 1.5.0 and that causes headaches. This shouldn't happen in future releases again.

**Comment by zilchulant** [comment]
As YogaSMC 1.5 made my hackintosh (Ideapad 5-15IIL05 with i7-1065g7) also kernelpanic, I am happy to see that it should work now. I will try the new version tomorrow, should have pretty similar outcome ✊

**Comment by Chris2fourlaw** [comment]
Here's the ioreg
[Chris’s MacBook Pro.zip](https://github.com/zhen-zen/YogaSMC/files/6528979/Chris.s.MacBook.Pro.zip)
