### ISSUE TITLE
Preferences Error - Thinkpad T460s Mac OS 11.3.1

### ISSUE THREAD

**Issue by meshackvictor** [zhen-zen/YogaSMC#142]
I have installed YogaSMC v1.5.0 on Thinkpad t460s running Mac os Big Sur 11.3.1. I can successfully control the fan but when i try to open the prefpane from the setting i get the following error

Preferences Error
Could not load YogaSMCPane preference pane.

I have tried the suggestions from #141  but it still doesn't seem to work.

Is there something that i am not doing right ? Thanks.

**Comment by zhen-zen** [comment]
So which prefpane (debug/release) do you have? Did it work by disabling SIP? (No idea why this works for some people)

**Comment by meshackvictor** [comment]
It now works, i think perhaps restarting helped. i am not sure.
