### ISSUE TITLE
How should Lenovo k29 modify SSDT to read and control fan speed

### ISSUE THREAD

**Issue by iDevon** [zhen-zen/YogaSMC#149]
My laptop is Lenovo k29
Add`HWFN` and `HWLO` in ssdt-think.aml, but the fan speed cannot be displayed and controlled,
How should I modify it?

>                     OperationRegion (ECOR, EmbeddedControl, Zero, 0x0100)
>                     Field (ECOR, ByteAcc, NoLock, Preserve)
>                     {
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                         Offset (0x01), 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                         Offset (0x02), 
>                         HIID,   8, 
>                             ,   5, 
>                             ,   2, 
>                         Offset (0x05), 
>                             ,   1, 
>                         Offset (0x06), 
>                         Offset (0x07), 
>                         Offset (0x08), 
>                         Offset (0x0B), 
>                         MLED,   2, 
>                         Offset (0x0C), 
>                         Offset (0x0D), 
>                         Offset (0x0E), 
>                             ,   2, 
>                         Offset (0x0F), 
>                             ,   6, 
>                             ,   1, 
>                         Offset (0x10), 
>                         SCI1,   1, 
>                         SCI2,   1, 
>                         Offset (0x11), 
>                         Offset (0x12), 
>                         Offset (0x13), 
>                         Offset (0x14), 
>                         Offset (0x15), 
>                         Offset (0x16), 
>                         Offset (0x17), 
>                         Offset (0x18), 
>                         HMPR,   8, 
>                         Offset (0x1A), 
>                         Offset (0x1B), 
>                         Offset (0x1C), 
>                         Offset (0x1D), 
>                         Offset (0x1E), 
>                         Offset (0x1F), 
>                         Offset (0x20), 
>                         Offset (0x23), 
>                         Offset (0x24), 
>                         Offset (0x26), 
>                             ,   2, 
>                             ,   2, 
>                         Offset (0x27), 
>                         Offset (0x2A), 
>                         Offset (0x2B), 
>                         Offset (0x2C), 
>                         Offset (0x2D), 
>                         Offset (0x2E), 
>                         Offset (0x2F), 
>                         Offset (0x30), 
>                             ,   6, 
>                             ,   1, 
>                         Offset (0x31), 
>                             ,   2, 
>                             ,   1, 
>                         Offset (0x32), 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                         Offset (0x33), 
>                             ,   1, 
>                         Offset (0x34), 
>                             ,   7, 
>                         Offset (0x35), 
>                         Offset (0x36), 
>                         Offset (0x38), 
>                             ,   7, 
>                         Offset (0x39), 
>                             ,   7, 
>                         Offset (0x3A), 
>                             ,   1, 
>                             ,   2, 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                         Offset (0x3B), 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                         Offset (0x3C), 
>                         Offset (0x46), 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                         Offset (0x47), 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                             ,   3, 
>                             ,   1, 
>                         Offset (0x48), 
>                             ,   1, 
>                             ,   1, 
>                             ,   2, 
>                             ,   1, 
>                             ,   1, 
>                             ,   1, 
>                         Offset (0x4E), 
>                         Offset (0x50), 
>                             ,   3, 
>                         HWLO,   1, 
>                         Offset (0x51), 
>                         HFNE,   1, 
>                         SNLK,   1, 
>                             ,   1, 
>                         HWFN,   1, 
>                             ,   1, 
>                         NULS,   1, 
>                             ,   1, 
>                         HMDN,   1, 
>                         DCWL,   1, 
>                         DCBD,   1, 
>                         DCWW,   1, 
>                             ,   4, 
>                         OVRQ,   1, 
>                         HFNS,   2, 
>                         Offset (0x58), 
>                         PWML,   8, 
>                         PWMH,   8, 
>                         Offset (0x5B), 
>                             ,   2, 
>                         HUBS,   1, 
>                         Offset (0x70), 
>                             ,   1, 
>                         HPLD,   1, 
>                             ,   3, 
>                         HPAC,   1, 
>                         Offset (0x71), 
>                         Offset (0x76), 
>                         HLCL,   8, 
>                         Offset (0x78), 
>                         Offset (0x79), 
>                         Offset (0x80), 
>                         Offset (0x81), 
>                         Offset (0x82), 
>                         Offset (0x83), 
>                         Offset (0x88), 
>                         HB0S,   7, 
>                         HB0A,   1, 
>                             ,   7, 
>                         Offset (0x8A), 
>                             ,   7, 
>                         Offset (0x8B), 
>                             ,   7, 
>                         Offset (0x8C), 
>                         DBG0,   8, 
>                             ,   3, 
>                             ,   3, 
>                         Offset (0x8E), 
>                         Offset (0x92), 
>                         CSSK,   1, 
>                         CTTK,   1, 
>                         DTTK,   1, 
>                         OSDK,   1, 
>                         VTPK,   1, 
>                         Offset (0x93), 
>                         Offset (0x95), 
>                         FSP1,   8, 
>                         Offset (0xA8), 
>                         TMP0,   8, 
>                         Offset (0xB0), 
>                         Offset (0xB4), 
>                         Offset (0xB8), 
>                         Offset (0xB9), 
>                         Offset (0xBA), 
>                         Offset (0xBE), 
>                         HSUN,   4, 
>                         Offset (0xBF), 
>                             ,   3, 
>                         HSPA,   1, 
>                         Offset (0xC0), 
>                             ,   4, 
>                         KBDL,   1, 
>                         Offset (0xC1), 
>                         APSL,   1, 
>                         TPDS,   1, 
>                         Offset (0xC8), 
>                         Offset (0xC9), 
>                         Offset (0xCA), 
>                         Offset (0xCC), 
>                         Offset (0xCD), 
>                         Offset (0xCE), 
>                         Offset (0xED), 
>                             ,   4, 
>                             ,   1
>                     }

>     Scope (_TZ)
>     {
>         Name (TBSE, 0x0AAC)
>         Name (CRT0, Zero)
>         Name (PSV0, Zero)
>         ThermalZone (TZS0)
>         {
>             Method (_TMP, 0, NotSerialized)  // _TMP: Temperature
>             {
>                 Local0 = \_SB.PCI0.LPCB.H_EC.THS0
>                 Local1 = \_SB.PCI0.LPCB.H_EC.KCSS
>                 Local2 = \_SB.PCI0.LPCB.H_EC.KOSD
>                 If (Local2)
>                 {
>                     If ((Local0 <= CRT0))
>                     {
>                         TSDL ()
>                         Local0 = (CRT0 + 0x02)
>                     }
>                 }
> 
>                 Return (C2K (Local0))
>             }
> 
>             Method (_CRT, 0, NotSerialized)  // _CRT: Critical Temperature
>             {
>                 Local0 = \_SB.PCI0.LPCB.H_EC.TSC0
>                 If (((Local0 >= 0x80) || (Local0 < 0x1E)))
>                 {
>                     Local0 = 0x78
>                 }
> 
>                 CRT0 = Local0
>                 Return (C2K (Local0))
>             }
>         }
> 
>         ThermalZone (TZS1)
>         {
>             Method (_TMP, 0, NotSerialized)  // _TMP: Temperature
>             {
>                 Local0 = \_SB.PCI0.LPCB.H_EC.THS1
>                 Return (C2K (Local0))
>             }
> 
>             Method (_CRT, 0, NotSerialized)  // _CRT: Critical Temperature
>             {
>                 Local0 = \_SB.PCI0.LPCB.H_EC.TSC1
>                 If (((Local0 >= 0x80) || (Local0 < 0x1E)))
>                 {
>                     Local0 = 0x78
>                 }
> 
>                 Return (C2K (Local0))
>             }
>         }
> 
>         Method (C2K, 1, NotSerialized)
>         {
>             Local0 = Arg0
>             If ((Local0 <= 0x10))
>             {
>                 Local0 = 0x1E
>             }
> 
>             If ((Local0 >= 0x7F))
>             {
>                 Local0 = 0x1E
>             }
> 
>             Local0 = ((Local0 * 0x0A) + TBSE) /* \_TZ_.TBSE */
>             Return (Local0)
>         }
>     }

**Comment by zhen-zen** [comment]
Only Think variant supports Fan reading and control via `HKEY`. Some new gaming laptops have fan reading support via WMI interface. There's no support for all other Idea variant laptops due to lack of documentation.
