### ISSUE TITLE
Laptop dies at low battery level notification

### ISSUE THREAD

**Issue by mhl221135** [zhen-zen/YogaSMC#150]
Maybe its a chance to implement laptop sleep/hibernate feature at low level notification in your project guys?
Maybe is some way to check battery warn level and send notification to sleep button ?
https://github.com/acidanthera/bugtracker/issues/1754

**Comment by zhen-zen** [comment]
There's only a `SLPB` device in ACPI scope and there's no control whether it triggers hibernation or sleep. If no ACPI patch is desired, it's better to implement it in SMCBatteryManager which already fetches battery level periodically.
