### ISSUE TITLE
SSDT-ECRW with ECEnabler?

### ISSUE THREAD

**Issue by nadiaholmquist** [zhen-zen/YogaSMC#153]
Laptop is a Lenovo Yoga 730-13IKB
([DSDT is here](https://github.com/zhen-zen/YogaSMC/files/7241240/DSDT.dsl.txt))

I'm using ECEnabler to get battery reading from the OS to work, and as far as I could see from the readme you additionally need SSDT-ECRW for RW access to the EC for YogaSMC, I added it but the preferences pane is still showing basic EC access.

Is this only compatible with using RehabMan's battery patching method, or do I need to adjust something else to get this to work? Also I'm not really sure how I should tell if the other SSDTs in the samples are necessary for this laptop or not?

**Comment by zhen-zen** [comment]
ECEnabler allows access by name using the native way. However, not all EC fields are named. And in the ThinkPad case, access by address is required to monitor fan speed and temperature etc.

You need to adjust the EC path in Rehabman's patch to match the one on yours. Other SSDT samples are referenced in readme.
