### ISSUE TITLE
Handle in kext?

### ISSUE THREAD

**Issue by CharlieJiangXXX** [zhen-zen/YogaSMC#154]
Instead of a concrete issue, this might be more of a suggestion. I am wondering if it is possible to handle some functions of YogaSMCNC in kernel space so that they would be available prior to logging in? For instance, on my ThinkPad E14 machine, the LED on mute only works after YogaSMCNC agent opens up, as well as the hotkeys other than the brightness & audio ones (I understand that the logos might be provided by the app). So is it possible to include such features in the kext?
Regards

**Comment by zhen-zen** [comment]
Actually I didn't find how to get current volume in kernel space. Current approach is provided by CoreAudio with AppleScript for backup, both are in user space. That's why I have to get an app / daemon to provide the functionality. Feel free to reopen the ticket if you have some more ideas.
