### ISSUE TITLE
Can't boot with YogaSMC.kext on ThinkPad X1C8

### ISSUE THREAD

**Issue by HJebbour** [zhen-zen/YogaSMC#156]
As said on the title, I cannot boot with YogaSMC.kext loaded on Lenovo ThinkPad X1 Carbon Gen 8 (20U9-0013FE).
My CPU: i7-10510U

**Comment by zhen-zen** [comment]
The kext is not designed for a specific system. You might need to go over your config files or upload logging / early boot screenshot for debugging. Close until more details are provided.

**Comment by HJebbour** [comment]
Thank you for your reply, please use this link to view the bootlogs (IMG) and OC (TXT) https://www.icloud.com/iclouddrive/08bbbhwfgA0w5ZaywjNZeSDZg#Logs

**Comment by zhen-zen** [comment]
I can't access the iCloud Drive. Can you just drag the attachment to the editor below?

**Comment by HJebbour** [comment]
![IMG_0898](https://user-images.githubusercontent.com/44072897/151874120-f3a1da42-4b3b-4441-99d4-1ea864afd0fe.jpg)
![IMG_1077](https://user-images.githubusercontent.com/44072897/151874140-0f26cd93-4169-43f2-aa65-c01c3eab506e.JPG)
[opencore-2022-01-31-185853.txt](https://github.com/zhen-zen/YogaSMC/files/7974301/opencore-2022-01-31-185853.txt)

Sorry for the inconvenience, here's again the logs.

**Comment by HJebbour** [comment]
Any update or do you want me to provide more logs? Thank you.

**Comment by zhen-zen** [comment]
To narrow down the issue, can you try removing either the `YogaHIDD` dict or the `ThinkVPC` dict in Info.plist ? Meanwhile, have you tried `YogaSMCAlter`?

**Comment by HJebbour** [comment]
Unfortunately none of the above worked, I even tried YogaSMCAlter without YogaHIDD & ThinkVPC dict.
![IMG_1130](https://user-images.githubusercontent.com/44072897/152854004-47c3a253-a182-4693-9ff9-7349d1920984.jpg)

**Comment by HJebbour** [comment]
Here's kernel panic log, I hope this can help:
[YogaSMC_kernel-panic.txt](https://github.com/zhen-zen/YogaSMC/files/8017970/YogaSMC_kernel-panic.txt)

**Comment by HJebbour** [comment]
I managed to boot with YogaSMC.kext when I removed one dict only (YogaWMI), but Yoga app and prefPane isn't working properly and ECAccess is Basic instead of RW, SSDT-ECRW is already loaded. The weird thing is, when I patched plist file and removed YogaWMI, after first reboot it detected the laptop as "Think" in Class with Think tab, but after second reboot and so, it shows "YogaHIDD" in class with no Think tab in preferences.
Please see below screenshots.

**First reboot**
![Screen Shot 2022-02-12 at 4 43 49 PM](https://user-images.githubusercontent.com/44072897/153718848-709f522c-7d19-4684-bb3e-4ef2aaf6908b.png)
![Screen Shot 2022-02-12 at 4 44 06 PM](https://user-images.githubusercontent.com/44072897/153718887-ad53cdd2-0716-441c-baaa-78e3c34491ea.png)
![Screen Shot 2022-02-12 at 4 44 14 PM](https://user-images.githubusercontent.com/44072897/153718889-b1fbb009-2041-404a-b4a8-faa54575522c.png)

**Second reboot**
![Screen Shot 2022-02-12 at 4 46 56 PM](https://user-images.githubusercontent.com/44072897/153718957-90478283-8df9-432e-b4ef-9d1dfb03e31b.png)

When I open the prefpane from system preferences for the second time it shows this
![Screen Shot 2022-02-12 at 4 47 16 PM](https://user-images.githubusercontent.com/44072897/153718996-b6ecbfe6-0541-4b72-b588-6881ca61c962.png)

**Comment by HJebbour** [comment]
I removed "YogaHIDD" dict from plist and now it is recognized as "Think". I replaced SSDT-ECRW with another one I found in a repo (I compared it with the sample file and IT'S THE SAME) and now ECAccess is RW, but I don't know how it worked even if it is the same file.
I don't know if I can add more features or enhance it (See below screenshots), but YogaSMC seems usable now with the patches I've done (of course with your help, and how you gave me the troubleshooting starting point with Info.plist)
![Screen Shot 2022-02-12 at 7 23 40 PM](https://user-images.githubusercontent.com/44072897/153723455-3bcd6975-671a-48a9-81c3-a6a97f9781f2.png)
![Screen Shot 2022-02-12 at 7 23 51 PM](https://user-images.githubusercontent.com/44072897/153723459-b1b0155c-51f3-4716-81ed-b88e678c9c5f.png)
![Screen Shot 2022-02-12 at 7 23 58 PM](https://user-images.githubusercontent.com/44072897/153723465-eb5e8e15-c75e-4c44-b8a2-3e7c55f7913a.png)

**Comment by zhen-zen** [comment]
I'm sorry for unable to response promptly. I have tested YogaHIDD coexistence earlier, but not sure why it was preferred on yours. Will look into that and find a fix.

**Comment by Baio1977** [comment]
I have identical problem, can't boot with YogaSMC.kext loaded on Lenovo Thinkpad T14 I5 10310U.[(https://github.com/Baio1977/Lenovo-Thinkpad-T14-)](https://github.com/Baio1977/Lenovo-Thinkpad-T14-)

**Comment by zhen-zen** [comment]
Closed as #173 is resolved. Please reopen if the issue persists.

**Comment by HJebbour** [comment]
> Closed as #173 is resolved. Please reopen if the issue persists.

With the new kext macOS is booting now, but pref is showing unsupported (see screenshot) and app is not doing anything.

https://user-images.githubusercontent.com/44072897/200417271-f8360048-6875-4fea-9e28-b13f60c4cf9c.png

**Comment by HJebbour** [comment]
> Closed as #173 is resolved. Please reopen if the issue persists.

With the new kext macOS is booting now, but pref is showing unsupported (see screenshot) and app is not doing anything.
![200417271-f8360048-6875-4fea-9e28-b13f60c4cf9c](https://user-images.githubusercontent.com/44072897/202849639-a25e5b74-40a2-44cb-b378-f24b6cedd577.png)

**Comment by Baio1977** [comment]
You need ACPI patches to have the desired functions, I've already written to you to see the repository of my T14 there is an SSDT that integrates everything you need.
https://github.com/zhen-zen/YogaSMC/tree/master/YogaSMC/SSDTSample
