### ISSUE TITLE
Possibility of disabling keyboard backlight OSD from YogaSMC?

### ISSUE THREAD

**Issue by verpejas** [zhen-zen/YogaSMC#160]
Hi, i use ThinkPad Assistant aswell, and it handles most of my funciton keys including backlight OSD info. How do I disable backlight OSD from YogaSMC?

**Comment by zhen-zen** [comment]
I don't support the idea to use two drivers with duplicated features and it's not supported.
However, you can try editing ` ~/Library/Preferences/org.zhen.YogaSMC.plist` manually after closing the app.
