### ISSUE TITLE
Cannot set battery threshold T460s

### ISSUE THREAD

**Issue by mikiotty** [zhen-zen/YogaSMC#162]
Hi!
When I set a battery threshold in the preference panel, every time I close it the setting resets itself. 
According to the app, I have EC read/write access, but it’s not working.

**Comment by zhen-zen** [comment]
It's weird that all ThinkPads share the same battery threshold interface. Can you share the kext log after setting those values?

**Comment by zhen-zen** [comment]
Close due to inactivity.
