### ISSUE TITLE
Failed to connect to YogaSMC on Lenovo Yoga (ThinkPad) S1

### ISSUE THREAD

**Issue by Dobikot** [zhen-zen/YogaSMC#166]
Hi! I tried to use YogaSMC and... i got this 
![photo_2022-07-19 17 09 34](https://user-images.githubusercontent.com/109461945/179771049-99221622-e3f0-49ae-b8f0-6d8bcc61d6d8.jpeg)
and i tried again and again, re looking to files and nothing...
If someone had a similar problem and solved it, then please help (here if someone needs my files in EFI)
![Снимок экрана 2022-07-19 в 17 17 29](https://user-images.githubusercontent.com/109461945/179772828-c3443e3c-e156-448b-889f-5930e352ccf1.png)
![Снимок экрана 2022-07-19 в 17 16 45](https://user-images.githubusercontent.com/109461945/179772842-548ef3d1-223d-4e03-a3ca-2db8af20a5b3.png)
![Снимок экрана 2022-07-19 в 17 16 26](https://user-images.githubusercontent.com/109461945/179772850-057e5f28-7fec-49f7-956c-1d99f4f1f5db.png)
thanks in advance to those who answer
(Sorry if my english is bad. I just from Ukraine)

**Comment by zhen-zen** [comment]
I'm not familiar with S serie. All past developments are based on ThinkPad X, T, E series. Although I can't guarantee it, can you upload the ACPI dump?

**Comment by Dobikot** [comment]
> 
Ok
here it is
[ACPI.zip](https://github.com/zhen-zen/YogaSMC/files/9289793/ACPI.zip)

**Comment by zhen-zen** [comment]
Please upload the dump of original ACPI tables instead of hotpatches.

**Comment by Dobikot** [comment]
what is ACPI dump? (yea I'm dumb)

**Comment by zhen-zen** [comment]
It seems to be a configuration issue now. Get familiar with the dortania guides, such as:
https://dortania.github.io/OpenCore-Install-Guide/config.plist/#adding-your-ssdts-kexts-and-firmware-drivers
https://dortania.github.io/Getting-Started-With-ACPI/
