### ISSUE TITLE
HP da1023nia has different interface in various product line

### ISSUE THREAD

**Issue by Edwardwich** [zhen-zen/YogaSMC#167]
APCI Dump :
https://github.com/Edwardwich/hp-DA1023nia-Hackintosh/tree/main/Opencore-Debug/SysReport/ACPI
ioreg:
[Ali’s MacBook Pro.zip](https://github.com/zhen-zen/YogaSMC/files/9150399/Ali.s.MacBook.Pro.zip)

![Screenshot 2022-07-20 at 6 24 22 PM](https://user-images.githubusercontent.com/35195176/180000005-e34239d4-b1ae-4415-aed1-6496a4d8a19f.png)

WFDE:
![Screenshot 2022-07-20 at 6 26 32 PM](https://user-images.githubusercontent.com/35195176/180000478-2acb42c4-ac9a-4f53-b90b-98c2dd831ccf.png)

WFTE:
![WFTE](https://user-images.githubusercontent.com/35195176/179998396-8c8b6967-6e0c-4ab9-9f73-037c5c09e9e6.png)
WMI1
![WMI1](https://user-images.githubusercontent.com/35195176/179998668-97e638bc-9e81-4cb2-965f-fb8c64ec8a38.png)
DYVPC:
![Screenshot 2022-07-20 at 6 19 09 PM](https://user-images.githubusercontent.com/35195176/179999296-0a7a59c5-5d7a-441a-9ccd-e10b6508e692.png)

**Comment by Mifaxav** [comment]
are hp's supported with yogasmc???

**Comment by Edwardwich** [comment]
> are hp's supported with yogasmc???

some HP supported
