### ISSUE TITLE
Errormsg on boot about deprecated kext "com.apple.iokit.iohidsystem"

### ISSUE THREAD

**Issue by benbender** [zhen-zen/YogaSMC#17]
````
dependency com.apple.iokit.iohidsystem fallback to com.apple.iokit.iohidfamily succeeded. Please fix your kext !
````

**Comment by zhen-zen** [comment]
This warning is possibly due to a transition to DriverKit. Let me check if just remove that dependency will work.

**Comment by benbender** [comment]
Yes it should. You can just change it in Info.plist and it's gone. Sorry, should have mentioned it. (Tested on Catalina & Big Sur)
