### ISSUE TITLE
Can't boot with YogaSMC.kext on ThinkPad T14 i5 10310U .....

### ISSUE THREAD

**Issue by Baio1977** [zhen-zen/YogaSMC#173]
I have the same problem that the user has on Thinkpad X1C8 same Series CPU CometLake. https://github.com/zhen-zen/YogaSMC/issues/156.
Here the Thinkpad T14 reposity, includes Ioreg + files extracted with EFI Debug.
EDIT:I was able to start with the YogaSMC.kext .
In the reposity you find all the files if you want to check.
https://github.com/Baio1977/Lenovo-Thinkpad-T14-

**Comment by zhen-zen** [comment]
So it works after removing the YogaHIDD entry?

**Comment by Baio1977** [comment]
Here is my Kext on the left and the original on the right.
As you can see I removed 2 items from the list.

![Screenshot 2022-10-09 alle 18 42 00](https://user-images.githubusercontent.com/59058746/194768988-9941dc32-05dc-4baa-a7b6-ce756f58f9fd.png)

**Comment by zhen-zen** [comment]
I'm still trying to figure out a way to clean up the mess when starting the WMI stuff.
Also I wonder if you can help to test whether it works by just removing only one of the items in the list.

**Comment by Baio1977** [comment]
TEST 1: removed from the plist only YogaHIDD the PC crashes in verbose.
TEST 2: removed from YogaWMI plist and PC boot regular, everything works.

YogaWMI is the problem.

THANK YOU.
For any evidence I am available.

**Comment by zhen-zen** [comment]
Can you try if #176 fix the issue?

**Comment by Baio1977** [comment]
One more block in verbose, the usual and right after a reboot

**Comment by zhen-zen** [comment]
Please try the latest build on the master branch. The issue should be fixed now.

**Comment by Baio1977** [comment]
Now it's ok I attach ioreg, I'll test this version and leave my comment here.
Thank you very much for your effort.
[YogaSMC 2.0 OK.zip](https://github.com/zhen-zen/YogaSMC/files/9844225/YogaSMC.2.0.OK.zip)

**Comment by HJebbour** [comment]
> Can you try if #176 could fix the issue? Also @HJebbour

With the new kext macOS is booting now, but pref is showing unsupported (see screenshot) and app is not doing anything.
![Screen Shot 2022-11-07 at 22 14 45](https://user-images.githubusercontent.com/44072897/200417271-f8360048-6875-4fea-9e28-b13f60c4cf9c.png)

**Comment by Baio1977** [comment]
https://github.com/HJebbour/ThinkPad-X1C8-Hackintosh this the EFI use ??
If you are missing ALL the ACPI part about it.
Post ioreg of your Thinkpad.

**Comment by HJebbour** [comment]
> https://github.com/HJebbour/ThinkPad-X1C8-Hackintosh this the EFI use ?? If you are missing ALL the ACPI part about it. Post ioreg of your Thinkpad.

Yes this is my EFI actually, but I don't understand your question?

**Comment by Baio1977** [comment]
Specific SSDTs are needed to be able to monitor the functions of the Kext YogaSMC.
Can you leave the ACPI files extracted from your Bios here ???

If you check my reposity you see everything I talk about.
(https://github.com/Baio1977/Lenovo-Thinkpad-T14-/blob/main/0.8.5/EFI/OC/ACPI/SSDT-T14Gen1.dsl)
