### ISSUE TITLE
Ventura - preferences button

### ISSUE THREAD

**Issue by georgezip** [zhen-zen/YogaSMC#185]
Please grant acces to apple event - error on ventura when preferences button is pressed

also there is:
Failed to open Preferences

please install YogaSMCPane

but YogaSMCPane is visible in preferences

**Comment by zhen-zen** [comment]
As it suggests, permission for Apple Events need to be granted for this function. The prompt will be asked during first run. If rejected; you have to navigate to system preferences and enable it manually.
