### ISSUE TITLE
Min MacOS version for kext / app to work.

### ISSUE THREAD

**Issue by Charlyo** [zhen-zen/YogaSMC#33]
Dear @zhen-zen and contributors. Thank you for this utility. However, in my T470 I'm still using macOS high Sierra. Is it compatible? Maybe the readme could reflect min version.

Nonetheless thank you for your time!

**Comment by zhen-zen** [comment]
Currently both the kext and the app target 10.12 and should work. However, I haven't got time to install that to 10.12.6 and test it.

**Comment by Charlyo** [comment]
Gonna try then! Thank you very much!
