### ISSUE TITLE
Preference pane not opening

### ISSUE THREAD

**Issue by Charlyo** [zhen-zen/YogaSMC#34]
Hi @zhen-zen again. 

Just tried your last release. The YogaSMCNC app is working but the preference pane is not opening.

Here's the console message:

`dlopen_preflight failed with dlopen_preflight(/Library/PreferencePanes/YogaSMCPane.prefPane/Contents/MacOS/YogaSMCPane): Library not loaded: @rpath/libswiftCore.dylib
`

**Comment by zhen-zen** [comment]
Sounds like swift framework issue. Can you try manually copy the `Contents/Frameworks` folder from the app into the prefpane?

**Comment by Charlyo** [comment]
Yup, it worked!

**Comment by zhen-zen** [comment]
Hmmm, can you try the prebuilt one again after installing https://support.apple.com/kb/DL1998?locale=en_US

**Comment by Charlyo** [comment]
Working after installing those!
