### ISSUE TITLE
Build YogaSMC locally

### ISSUE THREAD

**Issue by Charlyo** [zhen-zen/YogaSMC#44]
Dear zhen-zen, thank you for all your work!

ATM I'm trying to build this kext locally, but I'm missing several sources / SDK on 10.15.7. 
Could you please provide sources / info regarding how to build all targets?

Thank you very much

**Comment by gongzhenjeef** [comment]
Please place debug version of Lilu and VirtualSMC in the folder. You also need to clone https://github.com/acidanthera/MacKernelSDK for SDK.

**Comment by zhen-zen** [comment]
Please place debug version of Lilu and VirtualSMC in the folder. You also need to clone https://github.com/acidanthera/MacKernelSDK for SDK.

**Comment by Charlyo** [comment]
Thank you very much!!
