### ISSUE TITLE
Incorrect graphic notification - F8 Wireless Toggle

### ISSUE THREAD

**Issue by H15teve** [zhen-zen/YogaSMC#47]
Device: X1 Carbon Gen 6
When turning on/off F8 wireless toggle, the icon indicates "Wireless Off" all the time.

**Comment by zhen-zen** [comment]
Both wifi and bluetooth are OS level implementations. I just tried that action and nothing's going wrong.
@tylernguyen do you have the same issue?

**Comment by tylernguyen** [comment]
@zhen-zen 

No, the toggle works perfectly for me, switching between On and Off

**Comment by zhen-zen** [comment]
Many thanks. Btw I wonder which wireless card are you using? I don't know about the api compatibility of itlwm.

**Comment by tylernguyen** [comment]
> Many thanks. Btw I wonder which wireless card are you using? I don't know about the api compatibility of itlwm.

I'm using the native Broadcom card.

**Comment by H15teve** [comment]
> Many thanks. Btw I wonder which wireless card are you using? I don't know about the api compatibility of itlwm.

hmmm，my wireless card is DW1830

**Comment by zhen-zen** [comment]
And did the wifi turn on / off actually work despite the OSD prompt?

**Comment by H15teve** [comment]
> And did the wifi toggle actually work despite the OSD prompt?

Yes I confirm. Though sometimes through a frequent switching my wireless card appears to be failed, OSD does indicate the failure.

**Comment by zhen-zen** [comment]
Can you try #49 ? The prebuilt binaries are in GitHub Actions.

**Comment by H15teve** [comment]
> Can you try #49 ? The prebuilt binaries are in GitHub Actions.

This time it works properly. Thanks for keep tracking^_^
