### ISSUE TITLE
PrefPane not working under macOS Big Sur

### ISSUE THREAD

**Issue by kasti0** [zhen-zen/YogaSMC#61]
error message translated from german:
"Error in System preferences: the system preference "YogaSMCPane" could not be loaded".

the prefpane was trusted under System> Security

**Comment by marianopela** [comment]
Try disabling SIP. I have SIP enabled by OC and I disabled it via Recovery (`csrutil disable`)

**Comment by kasti0** [comment]
do you need to keep it disabled?

**Comment by marianopela** [comment]
> do you need to keep it disabled?
> and is it displaying anything for you?

I did nothing else and now SIP is showing as enabled (strange but also cool, as I liked it on) but pane is still working

Yes, it is displaying all the infos currently implemented and working for Ideapad devices

**Comment by kasti0** [comment]
That worked!
