### ISSUE TITLE
Kext and application for Big Sur?

### ISSUE THREAD

**Issue by htrung4** [zhen-zen/YogaSMC#72]
Hello,
Thank you for the very nice kext and application. It's working perfectly with Catalina the latest, but broken on Big Sur (the icon is broken, for example when pressing micmute). 
Hardware: Thinkpad L380
CPU: i5-8250U
GPU: UHD 620
SSD: 970 Evo plus 1TB

<img width="1366" alt="Screenshot 2020-11-18 at 22 53 16" src="https://user-images.githubusercontent.com/9250289/99592926-29cba080-29f1-11eb-93ce-0c126b82aa73.png">

**Comment by zhen-zen** [comment]
You will need to move the app into `/Applications` as prompted at startup for proper resources handling.

**Comment by htrung4** [comment]
I already copy it into applications. It's strange: if I copy the app first into applications and open it, then install the setting (yogasmcpane), it will not work. But if I install the setting first, then copy the app into application and open it, then it works. And, it's fixed now. Thank you for your amazing app.
