### ISSUE TITLE
Thinkpad T450s - Fan speed control isn't working

### ISSUE THREAD

**Issue by i3p9** [zhen-zen/YogaSMC#83]
Currently running `REL-130-2020-11-11` version of YogaSMC, on Catalina 10.15.7. Opencore 0.6.4, VirtualSMC 1.1.9, Lilu 1.5.0

Issue: Fan speed control is not working.

After installing the Kext, I can see the fan speed properly in third party apps like iStat Menu/MacFanControl but there's no way to control them. Also strangely, YogaSMCNC panel can't read fan speed. I think maybe because it says DYTCFunction: unsupported.

Screenshots of YogaSMCNC:
![image](https://user-images.githubusercontent.com/8825262/101419170-b0e9a580-3919-11eb-9873-4f0192a97e33.png)

![image](https://user-images.githubusercontent.com/8825262/101419197-ba730d80-3919-11eb-9b74-cc052648adb9.png)

And another thing is when opening YogaSMCNC, there's this message about EC not loading: 
![image](https://user-images.githubusercontent.com/8825262/101419130-9c0d1200-3919-11eb-9108-17adcc7d32f4.png)

For now, all I want is the ability to control Fan Speed. Please let me know if there's any information I can provide, I've switched to the debug kext to provide any info if necessary.

**Comment by zhen-zen** [comment]
Please merge `SSDT-RCSM.dsl` in `SSDTSample` into your battery hotpatch or as a standalone one after checking for conflict.

**Comment by i3p9** [comment]
I just tried loading `SSDT-RCSM` patch but it didn't work unfortunately. My battery patches are here: https://github.com/i3p9/Hackintosh-BigSur-Catalina-OpenCore-Lenovo-T450s-efi/tree/master/EFI/OC/ACPI

Can you let me know how to check for conflicts? I'm very new to patching and willing to learn. Do I check for conflicting definitions in the dsl files?

**Comment by zhen-zen** [comment]
Add `WE1B` and `WECB` methods to your `SSDT-BAT` at the same scope of `RE1B` and `RECB`.

**Comment by zhen-zen** [comment]
I'm closing this issue since it's not related to the driver. If the it still won't work, please continue the discussion in https://github.com/zhen-zen/YogaSMC/discussions?discussions_q=category%3A%22ACPI+Patching%22

**Comment by VinylNerd** [comment]
> Add `WE1B` and `WECB` methods to your `SSDT-BAT` at the same scope of `RE1B` and `RECB`.

im confused how to do this, could you please link to somewhere which explains as id love to get this working and dont have ec is RO because havnt done this.

**Comment by zhen-zen** [comment]
Please see https://github.com/zhen-zen/YogaSMC#ec-reading and the sample SSDT hotpatch at https://github.com/zhen-zen/YogaSMC/blob/master/YogaSMC/SSDTSample/SSDT-ECRW.dsl.

**Comment by VinylNerd** [comment]
> Please see https://github.com/zhen-zen/YogaSMC#ec-reading and the sample SSDT hotpatch at https://github.com/zhen-zen/YogaSMC/blob/master/YogaSMC/SSDTSample/SSDT-ECRW.dsl.

sorry, this doesnt make any sense to me, if you could explain in a more simple way that would help alot, thanks!

**Comment by zhen-zen** [comment]
Unfortunately there's no easy way to do that. Most people have to read Rehabman's manual in the readme. Current hotpatch approach is already simplified a lot. Dortania's ACPI guide is also a good staring point: https://dortania.github.io/Getting-Started-With-ACPI/.

**Comment by Zkingtut** [comment]
Hello @zhen-zen 
Please I will be so grateful if you explain me why is that ACPI Error , Everything is working fine but I've to investigate why Windows restart sometimes BSOD ( blue screen with ACPI Bios error ) .
if I delete that RE1B - there is no fans and I got Yoga error .. something like ECRW.dsl 
really I don't know and need your advice . Laptop Lenovo Thinkpad P50
thank you
<img width="1188" alt="Error ACPI" src="https://user-images.githubusercontent.com/54157851/187098782-1c95cd65-ab95-40f6-81d8-4c3b3ded1a49.png">

**Comment by zhen-zen** [comment]
> Hello @zhen-zen 
> 
> Please I will be so grateful if you explain me why is that ACPI Error , Everything is working fine but I've to investigate why Windows restart sometimes BSOD ( blue screen with ACPI Bios error ) .
> 
> if I delete that RE1B - there is no fans and I got Yoga error .. something like ECRW.dsl 
> 
> really I don't know and need your advice . Laptop Lenovo Thinkpad P50
> 
> thank you
> 
> <img width="1188" alt="Error ACPI" src="https://user-images.githubusercontent.com/54157851/187098782-1c95cd65-ab95-40f6-81d8-4c3b3ded1a49.png">
> 
> 
> 

Sorry I clicked edit instead of quote reply earlier.

Usually it means you already have RE1B in another SSDT, such as the battery hotpatch one. Just removed the duplicated method in the sample SSDT. Also I don't think it's related to BSOD since this method is only used for fan control.
