### ISSUE TITLE
Bluetooth Enable/Disable Hotkey

### ISSUE THREAD

**Issue by xuandung38** [zhen-zen/YogaSMC#94]
Can i have bluetooth Enable/Disable Hotkey like thinkpad assistian ?

**Comment by zhen-zen** [comment]
That function is already assigned to key `TP_HKEY_EV_BLUETOOTH`: `0x1314` for action `.bluetooth` https://github.com/zhen-zen/YogaSMC/blob/master/YogaSMCNC/Configuration.swift#L100

It should work ootb if yours have that key. And you can also customize it in the configuration.

**Comment by xuandung38** [comment]
How to get keycode combo ? Like FN + Shift + f8

**Comment by zhen-zen** [comment]
Fn keys are different from PS2 ones and there are no modifiers like `Shift`.

**Comment by zhen-zen** [comment]
However, it should be possible to listen to modifiers and add extra states to a key. Since EC key press is a one time event without separate up/down, the modifier should be held during that.
